---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Custom Oracle User Provider
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  ProviderImageUri:
    Type: String
    Description: Docker image URI to use
    Default: ''

Conditions:
  UseCustomProviderImageUri: !Not
    - !Equals ["", !Ref ProviderImageUri]

Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNCustomDBUserProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              - '*'
          - Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
            Effect: Allow
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNDBUserProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaPolicy
    Properties:
      Description: CloudFormation Custom:OracleUser implementation
      PackageType: Image
      Code:
        ImageUri: !If
          - UseCustomProviderImageUri
          - !Ref ProviderImageUri
          - 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-oracle-user-provider:1.1.0
      VpcConfig:
        SecurityGroupIds:
          - !Ref 'SecurityGroup'
        SubnetIds: !Ref 'Subnets'
      FunctionName: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-oracle-user-provider-${VPC}'
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
