---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds: !Ref 'Subnets'
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      LicenseModel: license-included
      Engine: oracle-se2
      EngineVersion: 19.0.0.0.ru-2024-10.rur-2024-10.r1
      CharacterSetName: WE8ISO8859P1
      VPCSecurityGroups:
        - !Ref 'DatabaseSecurityGroup'
      DBName: XE
      MasterUsername: root
      MasterUserPassword: !GetAtt 'DBPassword.Secret'
      MultiAZ: false
      Port: 1521
      PubliclyAccessible: 'false'
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      DBParameterGroupName: !Ref 'DatabaseParameterGroup'
      AllocatedStorage: 10
      DBInstanceClass: db.t3.medium
    DeletionPolicy: Snapshot
  DatabaseParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameters for Oracle CRDB1
      Family: oracle-se2-19
      Parameters: {}

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: oracle access
      VpcId: !Ref 'VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '1521'
          ToPort: '1521'
          SourceSecurityGroupId: !Ref 'SecurityGroup'
      SecurityGroupEgress: []
      Tags:
        - Key: Name
          Value: !Sub 'oracle.${AWS::StackName}'

  DBPassword:
    Type: Custom::Secret
    Properties:
      Name: !Sub '/${AWS::StackName}/oracle/root/password'
      Alphabet: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      MaxLength: 30
      ReturnSecret: true
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'

  OracleUserPassword:
    Type: Custom::Secret
    Properties:
      Name: !Sub '/${AWS::StackName}/oracle/scott/password'
      MaxLength: 30
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'

  OracleUser:
    Type: Custom::OracleUser
    DependsOn:
      - Database
      - DBPassword
      - OracleUserPassword
    Properties:
      User: SCOTT
      PasswordParameterName: !Sub '/${AWS::StackName}/oracle/scott/password'
      Database:
        User: root
        Host: !GetAtt 'Database.Endpoint.Address'
        Port: !GetAtt 'Database.Endpoint.Port'
        DBName: XE
        PasswordParameterName: !Sub '/${AWS::StackName}/oracle/root/password'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-oracle-user-provider-${VPC}'
